### PR TITLE
Work around GCC "maybe uninitialized" warning

### LINKED ISSUE #916: Compilation failed archlinux
**System**
OS: Archlinux
Branch: v0.71.532

**Step to reproduce**
```bash
$ git clone github.com/turanszkij/wickedengine --recursive --branch=v0.71.532
$ cd wickedengine
$ cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
$ cmake --build build -j 12
```

**logs**
```cmake
[  0%] Copying Content
[  5%] Built target FAudio
[ 11%] Built target Utility
[ 20%] Built target LUA
[ 56%] Built target Jolt
[ 56%] Building CXX object WickedEngine/CMakeFiles/WickedEngine_Linux.dir/wiScene_Serializers.cpp.o
[ 56%] Built target Content
/home/tonitch/WickedEngine/WickedEngine/wiScene_Serializers.cpp: In member function ‘void wi::scene::ArmatureComponent::Serialize(wi::Archive&, wi::ecs::EntitySerializer&)’:
/home/tonitch/WickedEngine/WickedEngine/wiScene_Serializers.cpp:879:51: error: ‘boneID’ may be used uninitialized [-Werror=maybe-uninitialized]
  879 |                                 boneCollection[i] = boneID;
/home/tonitch/WickedEngine/WickedEngine/wiScene_Serializers.cpp:877:40: note: ‘boneID’ was declared here
  877 |                                 Entity boneID;
      |                                        ^~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [WickedEngine/CMakeFiles/WickedEngine_Linux.dir/build.make:930: WickedEngine/CMakeFiles/WickedEngine_Linux.dir/wiScene_Serializers.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:291: WickedEngine/CMakeFiles/WickedEngine_Linux.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### PR DESCRIPTION
**Pull request by brakhane**
GCC 14.2 can't tell that SerializeEntity will initialize it, so disable the warning, otherwise it will fail the build if -Werror is active (which is the case for CMake atm)

Fixes #916

### CODE REVIEW

**Review by turanszkij — CHANGES_REQUESTED** [review]
It would be better to initialize boneID to INVALID_ENTITY. These pragmas won't compile on ps5 and it's a mess to ifdef them every time.

**Comment by brakhane** [comment]
I can do that, but I just realized, wouldn't `SerializeEntity(archive, &boneCollection[i], seri)` also work?

**Comment by turanszkij** [comment]
that would work too

**Comment by brakhane** [comment]
ok, then I'll do that, saves a copy I guess

**Review by turanszkij — APPROVED** [review]

**Pull request merged**
