### PR TITLE
New resource binding model

### PR DESCRIPTION
**Pull request by turanszkij**
See issue #145

### CODE REVIEW

**Comment by turanszkij** [comment]
Draft for new resource binding model:
- developer will declare root signature layout
- developer will allocate descriptor tables
- developer will declare root signatures for PSOs and compute shaders
- developer will write descriptors into tables with simple interface
- developer will bind root signatures
- developer will bind descriptor tables, root descriptors, root constants
- system will ensure that latest changes in descriptor tables are shader visible

TODO:
- implement for Vulkan device
- implement for DX11 device optionally if feasible
- modify all engine code to comply

#146

**Comment by turanszkij** [comment]
- Developer will be responsible to manage CPU threading and descriptor table writes

**Comment by turanszkij** [comment]
Problems:
- root constant / push descriptor syntax changes are maintainable between dx12 and vulkan with ConstantBuffer<T> syntax, but not feasible with dx11, which doesn't support ConstantBuffer<T> syntax
- shader visibility flags very differently set between dx12 and vulkan. Probably best to just use always all stages?
- dx12 descriptor spaces / vulkan descriptor set numbers mismatch: don't know yet how to handle nicely

**Comment by amerkoleci** [comment]
Not sure if all this stuff simplifies developers life, maybe a fallback to easier mode will be welcome probably, for dx12 and vulkan experts all this stuff is easy, newcomes will suffer

**Comment by turanszkij** [comment]
> Not sure if all this stuff simplifies developers life, maybe a fallback to easier mode will be welcome probably, for dx12 and vulkan experts all this stuff is easy, newcomes will suffer

Thanks for the feedback, that is definitely a concern. I will try to provide a simple interface here that is possibly simpler than the old model, however, it will require a change of mindset.

**Comment by turanszkij** [comment]
Changes:
- removed root descriptors (vulkan has dynamic buffers instead, works very differently)
- WriteDescriptor() will handle arrayIndex for descriptor arrays
- WriteDescriptor() can take buffer offset
- static samplers now part of DescriptorTable
- DescriptorTable bind point = HLSL descriptor "space" (to keep consistent model between dx12 and vulkan)
- DescriptorTable can have both samplers and resources inside it (dx12 will handle the separation in the backend)
- Root constants: specify byte size (instead of uint32_t count) at declare time, not when binding (to comply with vulkan)
- User doesn't need to bind RootSignature, it is bound automatically with PSO/ComputeShader/RaytracingPipelineState

Problems:
- Root descriptor (dx12) is different than dynamic buffer (vulkan). Root descriptor is a lot more convenient to use, but need to figure out how to handle efficiently with vulkan. It could be just a vkCmdBindDescriptorSets() with the offsets, but how to detect if the table needs allocation?

**Comment by turanszkij** [comment]
Changes:
- Root descriptors implemented: developer declares them within DescriptorTable (to match vulkan), but actually binding is following the more convenient dx12 model. 
- refactors

Problems:
- Indexing the root descriptors could be weird (index them just within themselves, not counting regular descriptors). Some more testing will reveal if this is a good behaviour or not.
- How to best ensure that very frequent small draws don't always start a new gpu visible heap entry (new descriptorset)? If this possible from backend side, that would be the best solution.

**Comment by turanszkij** [comment]
Implemented in 9723d94d906fe6dda527cc4a8e5b1c86ec54c374 
The old binding model can still be used

**Pull request closed without merging**
