### PR TITLE
Font outline

### PR DESCRIPTION
**Pull request by CaminoOnPc**
Added simple font outline code, in theory, can be drawn more efficiently but performance impact from this method is basically negligible so shouldn't matter for now

### CODE REVIEW

**Review by turanszkij — COMMENTED** [review]
I don't really like this solution. It produces many draw calls, but more importantly it doesn't look good (in my opinion), see attached image.


Quality can be improved by adding more draw calls that expand the outline diagonally too.

But I'd rather not add outline support at this point.

**Comment by BluePrintRandom** [comment]
in blender they have a system to extrude / bevel text

you can use this to produce normals on the bevel - and then use

dot(normal, local_up) to pull out 2 tones
https://www.youtube.com/watch?v=MFcUVU_JPV0
that is how these icons are made

**Comment by turanszkij** [comment]
It is a texture based font being used here, so I don't see how that would work.

**Comment by BluePrintRandom** [comment]
ah - blender tesselates a svg or font to create a model

this may be a neat shader to have (3d text from 2d font etc)

**Pull request closed without merging**
