### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by amerkoleci**
Updates various third party libraries and vulkan to latest heades.

### CODE REVIEW

**Comment by turanszkij** [comment]
Could you add the dxcompiler update also to this branch too so that it's updated as one? Also, this is a lot of changes, how much did you test that it doesn't break things?

**Comment by amerkoleci** [comment]
> Could you add the dxcompiler update also to this branch too so that it's updated as one? Also, this is a lot of changes, how much did you test that it doesn't break things?

I tested by running all samples and editor, loading scenes etc

**Comment by turanszkij** [comment]
Thanks. It should also be tested by running with the different rendering APIs too. However, I will also do some test runs on my side.

**Comment by amerkoleci** [comment]
> Thanks. It should also be tested by running with the different rendering APIs too. However, I will also do some test runs on my side.

Yes, I tested d3d11, d3d12 and vulkan, loaded sponza and other scenes, run tests etc

**Review by turanszkij — APPROVED** [review]

**Comment by turanszkij** [comment]
Thanks for the updates and testing!

**Pull request merged**
