### PR TITLE
atmosphere and volumetric cloud updates

### PR DESCRIPTION
**Pull request by Kliaxe**
Hi turanszkij!

Yet another clouds and atmosphere update. In this PR I added ground contribution lighting for the clouds. Normally a lot of light is hitting the surface of earth and bounces up onto to clouds, which we haven't accounted for, until now. This makes the clouds look even more realistic, and it's actually beginning to look a lot like what you'd see outside your window, which is quite impressive for real-time graphics. I'm impressed of how this has turned out, but I'm still very concerned about performance. Volumetric clouds in general is a very expensive effect. Should we let this effect be enabled by default, or disabled where the user manually can turn it on at will?

Another stuff in this PR is regarding ghosting and cutout artefacts which appears when geometry is moving in front of clouds. I also noticed an issue with the atmosphere, where the sun would be below the planet, but you'd still see a red solid color. These issues has been fixed in this PR.

Anyway I'm happy to contribute yet again! Keep up the good work!

Comparison of ground contribution effect: (ON/OFF)
clouds ON
clouds OFF

Comparison of atmosphere fix: (ON/OFF)
atm ON
atm OFF

### CODE REVIEW

**Comment by turanszkij** [comment]
This is really good improvement. The ghosting is basically gone, and the directional light behaves more consistently.

> Volumetric clouds in general is a very expensive effect. Should we let this effect be enabled by default, or disabled where the user manually can turn it on at will?

The expensive effects like most post processes are turned off by default to get the fastest performance by default, and this falls into this category. But perhaps it would be better if the volumetric clouds could act on the weather's cloudiness factor, so by default (cloudiness = 0) the post process would be a pass-through/disabled, and it would properly scale itself with higher values of the cloudiness parameter. (so cloudiness = 1 would be totally overcast). I'm not sure such a dynamic cloudiness is possible to be implemented this way. (for example now the depth of field post process is enabled by default, but only really running when camera parameters are set up for depth of field)
Let me know what you think about this.

Thanks a lot, I will merge this now as it is already a great improvement!

**Comment by Kliaxe** [comment]
> Should we let this effect be enabled by default, or disabled where the user manually can turn it on at will?

Oh I actually meant the contribution effect haha. I read somewhere in #261 that you were considering exposing some of the cloud parameters, which I think could be interesting! If you do expose some of them, do you think there would be enough space inside the weather window? I had a crazy idea if the engine could support tabs UI for a window, but thats just loose thoughts.

> But perhaps it would be better if the volumetric clouds could act on the weather's cloudiness factor ...

Right now the clouds has two parameters, `g_CoverageAmount` and `g_CoverageMinimum`, which controls the cloudiness. `g_CoverageAmount` is just a multiplier for our weather map, where we probably could use that as the cloudiness, but `g_CoverageMinimum` is at the same time also needed to create totally overcast. So a single cloudiness value (0 to 1) from clear to overcast is a bit difficult to do with this setup, but as far as I can tell it's totally possible to implement.

**Comment by turanszkij** [comment]
> I actually meant the contribution effect
So the new effect has to be enabled through code now? I missed it then.

Somehow unifying the weather and volumetric clouds is planned, but true that the weather window is one of the problems. Having a window tab support would be good, I am not sure when I get around to implementing it. I'll try playing with the cloud coverage sometime and see how it works.

**Comment by Kliaxe** [comment]
Sorry I miscommunicated the whole thing. All in all I just suggested if performance was a concern, we could make the contribution effect something the user could enable themselves with eg. a checkbox, to save some performance with clouds enabled.

If you do get around to test the coverage parameters, I found that values like 1.5 for `g_CoverageMinimum` looks nice for overcast clouds. But for the most part, the weather map plays a significant role of how to clouds look. These values I've referenced, for instance, manipulates that pre-generated weather map. We can make all sorts of weird shapes inside the weather map generator, and adjust it accordingly with the global parameters from the cloud render pass.

**Comment by turanszkij** [comment]
I think it would make sense to expose some post process settings, like the samplecount and such that control performance. It is also an option to reduce the rendering resolution of the effect. 

I've also tried the coverage settings quickly, they should definitely be exposed too as part of the weather. 

I'm working on some other stuff at the moment, but I'd like to get around to it soon.

**Comment by turanszkij** [comment]
Updated the volumetric clouds:
- added light shaft occlusion support
- moved into weather
- parameter access from c++, serialization

I only added the enable, coverageamount and coveragemin controls to the weather window as there are a lot of other parameters I didn't experiment with.

**Pull request merged**
