### PR TITLE
Make dofile return results

### PR DESCRIPTION
**Pull request by EmptySetRBLX**
Currently dofile returns a PID value, but this seems to be a input argument into the function anyways.

Most Lua implementations for dofile return the results of the dofile execution. Only easyish way currently to get the results from executing another Lua script in a Lua script is something like

`
print(loadfile("../Content/scripts/exampleScript.lua")())
`

or a require call if you don't mind the caching, although I don't think you get some of the globals set in dofile if you do any of these alternatives

### CODE REVIEW

**Comment by turanszkij** [comment]
This would break anyone's script that relies on current behaviour of dofile. If you don't give it PID argument, it will generate one internally.

**Comment by EmptySetRBLX** [comment]
@turanszkij 
Only 0 is ever generated as the PID in my testing unless explicitly passed

image

Should the auto generated PID be incrementing? Would adding the PID as the first output variable be acceptable to get this merged? That would handle current use cases if someone is relying on this PID return.

**Comment by turanszkij** [comment]
@megumumpkin Do you have any thoughts about this? Asking because you created the script tracking PID for lua, looks like it always sets the PID for dofile to zero when you call it from Lua (in Internal_DoFile()), but it generates unique PID if you call it from C++ (in RunFile()). I personally never used the return value of dofile.

**Comment by turanszkij** [comment]
@EmptySetRBLX You could add your dofile status as the second return value since lua supports multiple returns.

**Comment by EmptySetRBLX** [comment]
RunFile does not pass an explicit pid, causing the value to default to the GeneratePID() function. I have changed the Lua side to replicate that behavior. If an explicit PID is not passed, it will now call the generation function. 

The PID is the first return value of dofile(), any values returned by the file itself are returned as additional values in a multireturn.

**Review by turanszkij — APPROVED** [review]

**Comment by turanszkij** [comment]
Thanks, I think this should be good now.

**Pull request merged**
