### PR TITLE
C++ 20 changes 

### PR DESCRIPTION
**Pull request by CitroenGames**
These changes wont effect C++ 17 but will aid in the conversion to C++ 20

### CODE REVIEW

**Comment by turanszkij** [comment]
I think there was some problem with generic_string that's why it was changed to u8string, but can't remember what.

**Comment by CitroenGames** [comment]
well you are converting it from u8 string to normal string so unless you change the return type that wont effect anything

**Comment by turanszkij** [comment]
I downloaded the build, it crashes outright.

**Comment by CitroenGames** [comment]
hmm weird lemme look on my side

**Comment by CitroenGames** [comment]
ah yes you are right! the editor crashes the template seems to work as usual let look into why this is happening and come up with a solution

**Comment by CitroenGames** [comment]
i have come up with a solution but i think at this point its just better to decline this PR or upgrade to c++ 20

**Comment by CitroenGames** [comment]
yea nah this PR is getting stupid

**Pull request closed without merging**
