### PR TITLE
Also reset the mouse delta position each frame

### PR DESCRIPTION
**Pull request by dpalais**
Reset to zero the SDL mouse delta position data for each frame.

### CODE REVIEW

**Comment by turanszkij** [comment]
What do you think about this @megumumpkin ? Was there an issue with mouse delta with SDL?

**Comment by dpalais** [comment]
Indeed, mouse delta position will always be non-null and repeated until the next mouse movement in a different direction. It's always cleared in WickedEngine for every frame but then it's copied from the current SDL state which is never nullified.

**Comment by Jontte** [comment]
In addition to this change I recommend we also enable accumulation of motion deltas that are being processed during the same frame on lines 79: 
```
-                    mouse.delta_position.x = event.motion.xrel;
-                    mouse.delta_position.y = event.motion.yrel;
+                    mouse.delta_position.x += event.motion.xrel;
+                    mouse.delta_position.y += event.motion.yrel;
```
In SDL2 the relative mouse motion values are given relative to the last event, and without this change we miss many relative mouse motion events if they are handled during the same frame. In master, the mouse moves very slow for me and I think that's because we are missing a large portion of the relative mouse motion events. With this change the responsivity is much better.

**Comment by dpalais** [comment]
Agreed. I have added the accumulation of motion delta to the PR.

**Review by turanszkij — APPROVED** [review]

**Pull request merged**
