### PR TITLE
Various updates

### PR DESCRIPTION
**Pull request by amerkoleci**
- Update DirectX headers to agility SDK 1.606.3
- Update D3D12MemAlloc to latest version.
- Update Vulkan headers to 1.3.221
- Update volk
- Update VMA

### CODE REVIEW

**Comment by turanszkij** [comment]
Thanks, I will need some time to test these

**Comment by amerkoleci** [comment]
> Thanks, I will need some time to test these

I already tested both D3D12 and Vulkan samples, editor etc

**Comment by turanszkij** [comment]
DDGI and surfel GI are broken, so I will need to investigate them

**Comment by turanszkij** [comment]
directional light in vulkan, in Sponza is broken, too

**Comment by amerkoleci** [comment]
> directional light shadow maps in vulkan, in Sponza is broken, too

OMG, why that? DXC update?

**Comment by turanszkij** [comment]
It seems both issues are caused by new DXC, because if I replace the dxcompiler.dll and dxil.dll in your branch with old ones, and rebuild shaders, problem goes away.

**Comment by amerkoleci** [comment]
> It seems both issues are caused by new DXC, because if I replace the dxcompiler.dll and dxil.dll in your branch with old ones, and rebuild shaders, problem goes away. So could you add the old dxcompiler.dll and dxil.dll back?

OFC yes, strange tho, reverted back

**Comment by amerkoleci** [comment]
Would be cool to understand what shader feature is causing recent DXC issue, so we can report to their github repo, as the version I've grabbed is marked as stable (https://github.com/microsoft/DirectXShaderCompiler/releases/tag/v1.7.2207)

**Review by turanszkij — APPROVED** [review]

**Comment by turanszkij** [comment]
Thanks, it looks good now.

**Pull request merged**
