### PR TITLE
Lua Live Update

### PR DESCRIPTION
**Pull request by megumumpkin**
Here's my design on Wicked Engine's Lua scripting live update system.
All scripts now support live reloading, added new mode for dofile to load scripts which are using the new script file path system. 
Variable persistence among reloads are explicitly declared by using D table.

### CODE REVIEW

**Review by turanszkij — CHANGES_REQUESTED** [review]
The live_reload_demo.lua doesn't work in the current state for me. When I open with the Editor: 
image
When I open with dofile command with `true` second param: 
image

**Review by megumumpkin — COMMENTED** [review]
Done

**Review by megumumpkin — COMMENTED** [review]
Done

**Comment by megumumpkin** [comment]
Can I add an option in the editor to run script between two path modes?

**Review by turanszkij — CHANGES_REQUESTED** [review]
As discussed in private, at the current state it is too complicated to use, requires mental effort from developer to program scripts for correct live reload usage. The script path behaviour can be useful as an improvement that is separate from live reload.

**Pull request closed without merging**
