### PR TITLE
Adding Wobble Animation for the scripting API

### PR DESCRIPTION
**Pull request by Ficelloo**
Hello, I think it would be cool to add this to the scripting api

### CODE REVIEW

**Review by turanszkij — CHANGES_REQUESTED** [review]
Yes, it can be added, but since you are adding binding for the wobbleAnim.amount, you should name the lua function as `SetWobbleAnimAmount()` instead of `SetWobbleAnimStrength()`. You could also consider adding the binding for wobble anim speed while you're at it.

**Comment by Ficelloo** [comment]
Should I make an exemple lua script for it ?

**Comment by turanszkij** [comment]
> Should I make an exemple lua script for it ?

Thanks for making the changes. No need to make an example script for it, though if you want it is ok to create one.

**Review by turanszkij — APPROVED** [review]

**Comment by Ficelloo** [comment]
Alright! then let's push the pr

**Pull request merged**
