### PR TITLE
PE: ImGui Docking Sample.

### PR DESCRIPTION
**Pull request by plemsoft**
I did not commit WickedEngine.sln , as i use 2022 , so you need to add the sample to the VS solution :)

### CODE REVIEW

**Comment by turanszkij** [comment]
Thanks, btw the default WickedEngine.sln is set up for Visual Studio 2022

**Comment by turanszkij** [comment]
Also, feel free to add this to the credits.txt under your name, for example as `Dear Imgui Docking sample` or what you prefer.

**Comment by plemsoft** [comment]
Just pulled the latest master and it was setup for:
# Visual Studio Version 16
VisualStudioVersion = 16.0.29519.87

So perhaps you forgot to commit the 2022 version ? , anyway i committed a new one for 2022 :)

**Comment by plemsoft** [comment]
Think everything is ready now.

**Comment by turanszkij** [comment]
Hm, weird, but it works the same way for me. Everything's good.

**Review by turanszkij — APPROVED** [review]

**Review by turanszkij — APPROVED** [review]

**Pull request merged**
