### PR TITLE
Update vma to latest version

### PR DESCRIPTION
**Pull request by amerkoleci**
- Update vma to latest version
- Use new VMA_MEMORY_USAGE_AUTO with VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT for readback and VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT for upload resources

### CODE REVIEW

**Comment by turanszkij** [comment]
It seems that at the moment `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT` flag has a major negative performance impact. Using `VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT` instead is better. Maybe there is some uncached memory read somewhere in engine code, I will investigate more.

**Comment by turanszkij** [comment]
This was the issue, writes optimized to XOR by compiler: 
image
Now everything seems good.

**Comment by amerkoleci** [comment]
> This was the issue, writes optimized to XOR by compiler: image Now everything seems good.

Nice!

**Review by turanszkij — APPROVED** [review]

**Comment by turanszkij** [comment]
Thanks for updating VMA, it's actually quite good that this issue came up, I'm gonna spend more time to track down if this issue exists anywhere else. But this PR can be merged.

**Pull request merged**
